/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecruiterLoginRouteImport } from './routes/recruiter.login'
import { Route as RecruiterDashboardRouteImport } from './routes/recruiter.dashboard'
import { Route as ApplyJobIdRouteImport } from './routes/apply.$jobId'
import { Route as RecruiterDashboardIndexRouteImport } from './routes/recruiter.dashboard.index'
import { Route as RecruiterDashboardSettingsRouteImport } from './routes/recruiter.dashboard.settings'
import { Route as RecruiterDashboardNotificationsRouteImport } from './routes/recruiter.dashboard.notifications'
import { Route as RecruiterDashboardJobsRouteImport } from './routes/recruiter.dashboard.jobs'
import { Route as RecruiterDashboardIntegrationsRouteImport } from './routes/recruiter.dashboard.integrations'
import { Route as RecruiterDashboardDatabaseRouteImport } from './routes/recruiter.dashboard.database'
import { Route as RecruiterDashboardAnalyticsRouteImport } from './routes/recruiter.dashboard.analytics'
import { Route as RecruiterDashboardJobsJobIdRouteImport } from './routes/recruiter.dashboard.jobs.$jobId'

const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterLoginRoute = RecruiterLoginRouteImport.update({
  id: '/recruiter/login',
  path: '/recruiter/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterDashboardRoute = RecruiterDashboardRouteImport.update({
  id: '/recruiter/dashboard',
  path: '/recruiter/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyJobIdRoute = ApplyJobIdRouteImport.update({
  id: '/apply/$jobId',
  path: '/apply/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterDashboardIndexRoute = RecruiterDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecruiterDashboardRoute,
} as any)
const RecruiterDashboardSettingsRoute =
  RecruiterDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => RecruiterDashboardRoute,
  } as any)
const RecruiterDashboardNotificationsRoute =
  RecruiterDashboardNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => RecruiterDashboardRoute,
  } as any)
const RecruiterDashboardJobsRoute = RecruiterDashboardJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => RecruiterDashboardRoute,
} as any)
const RecruiterDashboardIntegrationsRoute =
  RecruiterDashboardIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => RecruiterDashboardRoute,
  } as any)
const RecruiterDashboardDatabaseRoute =
  RecruiterDashboardDatabaseRouteImport.update({
    id: '/database',
    path: '/database',
    getParentRoute: () => RecruiterDashboardRoute,
  } as any)
const RecruiterDashboardAnalyticsRoute =
  RecruiterDashboardAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => RecruiterDashboardRoute,
  } as any)
const RecruiterDashboardJobsJobIdRoute =
  RecruiterDashboardJobsJobIdRouteImport.update({
    id: '/$jobId',
    path: '/$jobId',
    getParentRoute: () => RecruiterDashboardJobsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/jobs': typeof JobsRoute
  '/apply/$jobId': typeof ApplyJobIdRoute
  '/recruiter/dashboard': typeof RecruiterDashboardRouteWithChildren
  '/recruiter/login': typeof RecruiterLoginRoute
  '/recruiter/dashboard/analytics': typeof RecruiterDashboardAnalyticsRoute
  '/recruiter/dashboard/database': typeof RecruiterDashboardDatabaseRoute
  '/recruiter/dashboard/integrations': typeof RecruiterDashboardIntegrationsRoute
  '/recruiter/dashboard/jobs': typeof RecruiterDashboardJobsRouteWithChildren
  '/recruiter/dashboard/notifications': typeof RecruiterDashboardNotificationsRoute
  '/recruiter/dashboard/settings': typeof RecruiterDashboardSettingsRoute
  '/recruiter/dashboard/': typeof RecruiterDashboardIndexRoute
  '/recruiter/dashboard/jobs/$jobId': typeof RecruiterDashboardJobsJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/jobs': typeof JobsRoute
  '/apply/$jobId': typeof ApplyJobIdRoute
  '/recruiter/login': typeof RecruiterLoginRoute
  '/recruiter/dashboard/analytics': typeof RecruiterDashboardAnalyticsRoute
  '/recruiter/dashboard/database': typeof RecruiterDashboardDatabaseRoute
  '/recruiter/dashboard/integrations': typeof RecruiterDashboardIntegrationsRoute
  '/recruiter/dashboard/jobs': typeof RecruiterDashboardJobsRouteWithChildren
  '/recruiter/dashboard/notifications': typeof RecruiterDashboardNotificationsRoute
  '/recruiter/dashboard/settings': typeof RecruiterDashboardSettingsRoute
  '/recruiter/dashboard': typeof RecruiterDashboardIndexRoute
  '/recruiter/dashboard/jobs/$jobId': typeof RecruiterDashboardJobsJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/jobs': typeof JobsRoute
  '/apply/$jobId': typeof ApplyJobIdRoute
  '/recruiter/dashboard': typeof RecruiterDashboardRouteWithChildren
  '/recruiter/login': typeof RecruiterLoginRoute
  '/recruiter/dashboard/analytics': typeof RecruiterDashboardAnalyticsRoute
  '/recruiter/dashboard/database': typeof RecruiterDashboardDatabaseRoute
  '/recruiter/dashboard/integrations': typeof RecruiterDashboardIntegrationsRoute
  '/recruiter/dashboard/jobs': typeof RecruiterDashboardJobsRouteWithChildren
  '/recruiter/dashboard/notifications': typeof RecruiterDashboardNotificationsRoute
  '/recruiter/dashboard/settings': typeof RecruiterDashboardSettingsRoute
  '/recruiter/dashboard/': typeof RecruiterDashboardIndexRoute
  '/recruiter/dashboard/jobs/$jobId': typeof RecruiterDashboardJobsJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/jobs'
    | '/apply/$jobId'
    | '/recruiter/dashboard'
    | '/recruiter/login'
    | '/recruiter/dashboard/analytics'
    | '/recruiter/dashboard/database'
    | '/recruiter/dashboard/integrations'
    | '/recruiter/dashboard/jobs'
    | '/recruiter/dashboard/notifications'
    | '/recruiter/dashboard/settings'
    | '/recruiter/dashboard/'
    | '/recruiter/dashboard/jobs/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/jobs'
    | '/apply/$jobId'
    | '/recruiter/login'
    | '/recruiter/dashboard/analytics'
    | '/recruiter/dashboard/database'
    | '/recruiter/dashboard/integrations'
    | '/recruiter/dashboard/jobs'
    | '/recruiter/dashboard/notifications'
    | '/recruiter/dashboard/settings'
    | '/recruiter/dashboard'
    | '/recruiter/dashboard/jobs/$jobId'
  id:
    | '__root__'
    | '/'
    | '/jobs'
    | '/apply/$jobId'
    | '/recruiter/dashboard'
    | '/recruiter/login'
    | '/recruiter/dashboard/analytics'
    | '/recruiter/dashboard/database'
    | '/recruiter/dashboard/integrations'
    | '/recruiter/dashboard/jobs'
    | '/recruiter/dashboard/notifications'
    | '/recruiter/dashboard/settings'
    | '/recruiter/dashboard/'
    | '/recruiter/dashboard/jobs/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JobsRoute: typeof JobsRoute
  ApplyJobIdRoute: typeof ApplyJobIdRoute
  RecruiterDashboardRoute: typeof RecruiterDashboardRouteWithChildren
  RecruiterLoginRoute: typeof RecruiterLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/login': {
      id: '/recruiter/login'
      path: '/recruiter/login'
      fullPath: '/recruiter/login'
      preLoaderRoute: typeof RecruiterLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/dashboard': {
      id: '/recruiter/dashboard'
      path: '/recruiter/dashboard'
      fullPath: '/recruiter/dashboard'
      preLoaderRoute: typeof RecruiterDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/$jobId': {
      id: '/apply/$jobId'
      path: '/apply/$jobId'
      fullPath: '/apply/$jobId'
      preLoaderRoute: typeof ApplyJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/dashboard/': {
      id: '/recruiter/dashboard/'
      path: '/'
      fullPath: '/recruiter/dashboard/'
      preLoaderRoute: typeof RecruiterDashboardIndexRouteImport
      parentRoute: typeof RecruiterDashboardRoute
    }
    '/recruiter/dashboard/settings': {
      id: '/recruiter/dashboard/settings'
      path: '/settings'
      fullPath: '/recruiter/dashboard/settings'
      preLoaderRoute: typeof RecruiterDashboardSettingsRouteImport
      parentRoute: typeof RecruiterDashboardRoute
    }
    '/recruiter/dashboard/notifications': {
      id: '/recruiter/dashboard/notifications'
      path: '/notifications'
      fullPath: '/recruiter/dashboard/notifications'
      preLoaderRoute: typeof RecruiterDashboardNotificationsRouteImport
      parentRoute: typeof RecruiterDashboardRoute
    }
    '/recruiter/dashboard/jobs': {
      id: '/recruiter/dashboard/jobs'
      path: '/jobs'
      fullPath: '/recruiter/dashboard/jobs'
      preLoaderRoute: typeof RecruiterDashboardJobsRouteImport
      parentRoute: typeof RecruiterDashboardRoute
    }
    '/recruiter/dashboard/integrations': {
      id: '/recruiter/dashboard/integrations'
      path: '/integrations'
      fullPath: '/recruiter/dashboard/integrations'
      preLoaderRoute: typeof RecruiterDashboardIntegrationsRouteImport
      parentRoute: typeof RecruiterDashboardRoute
    }
    '/recruiter/dashboard/database': {
      id: '/recruiter/dashboard/database'
      path: '/database'
      fullPath: '/recruiter/dashboard/database'
      preLoaderRoute: typeof RecruiterDashboardDatabaseRouteImport
      parentRoute: typeof RecruiterDashboardRoute
    }
    '/recruiter/dashboard/analytics': {
      id: '/recruiter/dashboard/analytics'
      path: '/analytics'
      fullPath: '/recruiter/dashboard/analytics'
      preLoaderRoute: typeof RecruiterDashboardAnalyticsRouteImport
      parentRoute: typeof RecruiterDashboardRoute
    }
    '/recruiter/dashboard/jobs/$jobId': {
      id: '/recruiter/dashboard/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/recruiter/dashboard/jobs/$jobId'
      preLoaderRoute: typeof RecruiterDashboardJobsJobIdRouteImport
      parentRoute: typeof RecruiterDashboardJobsRoute
    }
  }
}

interface RecruiterDashboardJobsRouteChildren {
  RecruiterDashboardJobsJobIdRoute: typeof RecruiterDashboardJobsJobIdRoute
}

const RecruiterDashboardJobsRouteChildren: RecruiterDashboardJobsRouteChildren =
  {
    RecruiterDashboardJobsJobIdRoute: RecruiterDashboardJobsJobIdRoute,
  }

const RecruiterDashboardJobsRouteWithChildren =
  RecruiterDashboardJobsRoute._addFileChildren(
    RecruiterDashboardJobsRouteChildren,
  )

interface RecruiterDashboardRouteChildren {
  RecruiterDashboardAnalyticsRoute: typeof RecruiterDashboardAnalyticsRoute
  RecruiterDashboardDatabaseRoute: typeof RecruiterDashboardDatabaseRoute
  RecruiterDashboardIntegrationsRoute: typeof RecruiterDashboardIntegrationsRoute
  RecruiterDashboardJobsRoute: typeof RecruiterDashboardJobsRouteWithChildren
  RecruiterDashboardNotificationsRoute: typeof RecruiterDashboardNotificationsRoute
  RecruiterDashboardSettingsRoute: typeof RecruiterDashboardSettingsRoute
  RecruiterDashboardIndexRoute: typeof RecruiterDashboardIndexRoute
}

const RecruiterDashboardRouteChildren: RecruiterDashboardRouteChildren = {
  RecruiterDashboardAnalyticsRoute: RecruiterDashboardAnalyticsRoute,
  RecruiterDashboardDatabaseRoute: RecruiterDashboardDatabaseRoute,
  RecruiterDashboardIntegrationsRoute: RecruiterDashboardIntegrationsRoute,
  RecruiterDashboardJobsRoute: RecruiterDashboardJobsRouteWithChildren,
  RecruiterDashboardNotificationsRoute: RecruiterDashboardNotificationsRoute,
  RecruiterDashboardSettingsRoute: RecruiterDashboardSettingsRoute,
  RecruiterDashboardIndexRoute: RecruiterDashboardIndexRoute,
}

const RecruiterDashboardRouteWithChildren =
  RecruiterDashboardRoute._addFileChildren(RecruiterDashboardRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JobsRoute: JobsRoute,
  ApplyJobIdRoute: ApplyJobIdRoute,
  RecruiterDashboardRoute: RecruiterDashboardRouteWithChildren,
  RecruiterLoginRoute: RecruiterLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
